### ISSUE TITLE
Hello there, How to select a QR code from the photo app to scan

### ISSUE THREAD

**Issue by liangsaifei** [Scandit/datacapture-android-samples#10]

**Comment by ScanditSupport** [comment]
Hi @liangsaifei 

It is possible to process a single image by passing it to our SDK for decoding. However, this feature's availability and exact code snippet depend on a platform. 

Could you please reach out to us directly with more details? 
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by liangsaifei** [comment]
yes,could you give me snippet code of  Android ?

**Comment by liangsaifei** [comment]
Hello there,thanks for your help ,i found the resolution, the doc link:https://docs.scandit.com/data-capture-sdk/android/core/api/image-frame-source.html .

Thank you very much.

**Comment by ScanditSupport** [comment]
Hi @liangsaifei 

Glad to hear you managed to find the needed resource already!

In case any more details questions arise, please contact us directly. 
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
