### ISSUE TITLE
Crash: UnsatisfiedLinkError: dlopen failed: library "libbar.so" not found

### ISSUE THREAD

**Issue by mtcn** [Scandit/datacapture-android-samples#13]
**Issue Description:**

In my Android app, several users have reported encountering a frequent crash, leading to an "UnsatisfiedLinkError." Despite numerous attempts, I have been unable to reproduce the issue myself. The error seems to be affecting a wide range of devices and Android OS versions. After inspecting the app's "lib" folder, I confirmed that "libbar.so" is present in all required ABIs, including x86, x86_64, arm64-v8a, and armeabi-v7a.

**Steps to Reproduce:**

Unfortunately, the crash cannot be reproduced consistently on any particular device or OS version during my testing.

**Libraries and Versions:**

We are using the Scandit Data Capture SDK in our app, with the following dependencies:

implementation ("com.scandit.datacapture:core:6.17.1")
implementation "com.scandit.datacapture:barcode:6.17.1"
implementation "com.scandit.datacapture:parser:6.17.1"

**Additional Information:**
- The crash appears to be common among users, indicating a widespread issue that needs urgent attention.
- The crash is not dependent on the device or Android OS version, making it challenging to pinpoint the cause.

![Screenshot 2023-07-19 at 22 31 25](https://github.com/Scandit/datacapture-android-samples/assets/13784221/a7056fc5-ad23-4392-be7f-dd650b928917)

**Comment by ScanditSupport** [comment]
Hi @mtcn,

As the solutions to this problem heavily depend on the individual integrations and may benefit from follow-up conversations, it could be confusing to some developers should these be posted here. I can see you have already filed a [Support ticket](https://support.scandit.com/hc/en-us/requests/new) and we will continue the conversation there.
