### ISSUE TITLE
Is scandit need androidX?

### ISSUE THREAD

**Issue by merenyimiklos** [Scandit/datacapture-android-samples#14]
I want to ask this questions:

is there a minimum Sdk Version what we need to use? (we use 24 now)
is there a minimum target Sdk Version what we need to use? (we use 25 now)

i got this error:

Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':app:stagingDebugCompileClasspath'.

And the package was download well, but i can't build the application to my phone.

is there any requirement what we need to put?

**Comment by ScanditSupport** [comment]
Hi @merenyimiklos,

Generally speaking, you can find the system requirements here:
https://docs.scandit.com/data-capture-sdk/android/requirements.html
The minimum Android version for the contemporary SDK is 6.0

Regarding the build error, can you please reach out to us directly and share a few snippets of your code on how you implemented Scandit? [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
