### ISSUE TITLE
Crash when remove node on activity destroy

### ISSUE THREAD

**Issue by quangpv** [Scandit/datacapture-android-samples#3]
When activity destroy, i have call remove node from DataCaptureContext and received crash
 
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'void com.scandit.datacapture.core.capture.DataCaptureContextListener.onModeRemoved(com.scandit.datacapture.core.capture.DataCaptureContext, com.scandit.datacapture.core.capture.DataCaptureMode)' on a null object reference
com.scandit.datacapture.core.capture.DataCaptureContext$b.onModeRemoved (SourceFile:306)
com.scandit.datacapture.core.capture.DataCaptureContextListenerReversedAdapter.onModeRemoved (SourceFile:49)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.HandlerThread.run (HandlerThread.java:67)

another way some time it crashing with another exception

Fatal Exception: java.util.ConcurrentModificationException
java.util.ArrayList$Itr.next (ArrayList.java:860)
com.scandit.datacapture.core.capture.DataCaptureContext$b.onModeRemoved (SourceFile:351)
com.scandit.datacapture.core.capture.DataCaptureContextListenerReversedAdapter.onModeRemoved (SourceFile:49)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.HandlerThread.run (HandlerThread.java:67)

Does it cause by my programming or something else ?, please help me !

**Comment by ScanditSupport** [comment]
Hi @quangpv, 

Scandit Support is happy to help you. Could you please reach out to support@scandit.com and share a code snippet which shows how you handle the DataCaptureContext?

**Comment by ScanditSupport** [comment]
View in Browser <[[https://go.scandit.com/v/NjA1LUVYQy0wMzQAAAGOeqxXOWYnqKgAltpGR12ii9UrTjvraZHNVOKk3o5zMIJmhsJDHIErLWaRc8h7-rXGG_L6Zic=]]>
We’re taking a closer look at in-store operations and bringing 
order fulfillment into the spotlight. Discover how our customers have reached tangible results with our product offering, and explore what the future has in store for retailers everywhere.
Join Our Upcoming 30-Minute Webinar
Looking for ways to boost your order fulfillment? Then attend our 
 next webinar (on the 18th of October at 1 PM BST), where we’ll break down how our customers have achieved 0% error picking rates, saved hundreds of thousands of dollars, and fulfilled 5x more orders. 

 

 
Register Now <https://go.scandit.com/NjA1LUVYQy0wMzQAAAGOeqxXOVM_EWLsIORn4C293X8B4-E7mZrDsXakzjvW3nGKvCXdfJVWyGzH1_mbMT6UgBSFMZg=>
Revolutionizing Retail Order Fulfillment
Our unique product offering gives retailers the ability to 
cut their costs and improve fulfillment rates — without expensive changes to infrastructure or processes. 

 

 
Start Your Revolution <https://go.scandit.com/NjA1LUVYQy0wMzQAAAGOeqxXOY0SD62CRGb_EZhD1O-CZkXclONMNjAhhU8WCyKnxxb0fE7EnxIHSIxkFa1_4HvA37A=>
New: Bricoman Case Study
By using Scandit Smart Data Capture, 
Bricoman employees can now effortlessly tackle daily tasks such as inventory management, order placement and fulfilment, and customer assistance. 

 

 
Hear From Bricoman <https://go.scandit.com/NjA1LUVYQy0wMzQAAAGOeqxXOfFBC2w7Y47t-1hi-nCd-vzneEaZzGwN0m3WAYi_9WaLd5Xgzw7cm4gPCDCfXB2RaXU=>
Democratizing Frontline Access To Data Insights
Penned by our 
CEO and Co-Founder, Samuel Mueller, this Forbes article details why offering frontline workers access to data should be high on your list of priorities. 

 

 
Set Your Priorities Straight <https://go.scandit.com/NjA1LUVYQy0wMzQAAAGOeqxXOQ7KXaIp-BPXPJ4GZczriPZsJdidHELjEeyNBXOQbhy5mAQVdRhl_h-MNe_NT4j6KIs=>
