### ISSUE TITLE
TextCaptureListener not calling after integration

### ISSUE THREAD

**Issue by sravanthiRaju** [Scandit/datacapture-android-samples#4]
Dear Team,

I created a license key that supports OCR. And I have integrated a sample app for **textrecognitionsampler** . 
I got the below error
Could not find com.scandit.datacapture::6.6.0.
 I add below APIs to solve this 
    api "com.scandit.datacapture:barcode:6.6.0"
    api "com.scandit.datacapture:parser:6.6.0"
    api "com.scandit.datacapture:text-base:6.6.0"
    api "com.scandit.datacapture:text:6.6.0"
    api "com.scandit.datacapture:id:6.6.0"

After I run the application and scan the text, nothing is showing, even not calling TextCaptureListener also. 
Please help me with the same.

Thank you

**Comment by ScanditSupport** [comment]
Hi @sravanthiRaju 
would you mind reaching out via https://support.scandit.com/hc/en-us/requests/new regarding your individual issue?
It would allow us to support you and take your particular setup and requirements into account.

Best regards
Scandit Support

**Comment by sravanthiRaju** [comment]
> Hi @sravanthiRaju
> would you mind reaching out via https://support.scandit.com/hc/en-us/requests/new regarding your individual issue?
> It would allow us to support you and take your particular setup and requirements into account.
> 
> Best regards
> Scandit Support

I sent to email but we are not getting any reply related to this. so how can I solve this issue?

**Comment by ScanditSupport** [comment]
Hi @sravanthiRaju 
we've received your request and have answered via email on the same day. 
Can you please check your inbox and spam folder? 
The answer has been sent on Dec 22nd, 19:08 CET with subject "TextCaptureListener not calling after integration".

Alternatively, you can sign up and log into the support portal under https://support.scandit.com/hc/en-us to see the answers in case emails are not coming through. 
Please note that you have to use the same email to sign up as you've used for sending the request earlier.
