### ISSUE TITLE
OCR text scan license

### ISSUE THREAD

**Issue by BlueClouDragon** [Scandit/datacapture-android-samples#5]
I am going to integrate scandit android SDK into our company product.
The Barcode feature works well, but I can't integrate the Text Recognition feature because of a license key.
Also, the barcode feature works with the trial key.
I sent many messages to support and submitted a Request. but did not get any response.
Is there any solution?

**Comment by ScanditSupport** [comment]
Hi, 
thanks for your comment. 
We've already answered your support request and your Text Recognition license key request is in approval state.

**Comment by BlueClouDragon** [comment]
Thanks for your help
I made new key and will test license key after integrate OCR feature
