### ISSUE TITLE
How to customize preview in android while scanning bar code

### ISSUE THREAD

**Issue by Yousaf128** [Scandit/datacapture-android-samples#9]
How to customize preview of scanning screen Top half screen show camera preview for scanning bar code and bottom of half screen show  bar code scanning result.

**Comment by ScanditSupport** [comment]
Hi @Yousaf128,

We have a sample that mirrors the functionality you desire, specifically, the '[splitview activity](https://github.com/Scandit/datacapture-android-samples/tree/master/BarcodeCaptureViewsSample/src/main/java/com/scandit/datacapture/barcodecaptureviewssample/modes/splitview)' of the [BarcodeCaptureViewsSample](https://github.com/Scandit/datacapture-android-samples/tree/master/BarcodeCaptureViewsSample).

Essentially you can just resize the [DataCaptureView's](https://docs.scandit.com/data-capture-sdk/android/core/api/ui/data-capture-view.html?highlight=datacaptureview#class-com.scandit.datacapture.core.ui.DataCaptureView) container according to your needs:
https://github.com/Scandit/datacapture-android-samples/blob/master/BarcodeCaptureViewsSample/src/main/res/layout/activity_split_view.xml

In case you have more detailed questions, please feel free to reach out to us directly: [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
